# This is the Containerfile for the fg-ubi image. It is used to build the fg-ubi image, which is a base image for the fg application. It is based on the Amazon Corretto 25 JDK image, which is a UBI image. The fg-ubi image includes the necessary dependencies for building and running the fg application, such as Maven and Node.js. The image also includes a minimal JRE created with jlink, which reduces the size of the image.

# IMAGE_NAME=fg-ubi
# REGISTRY_USER_NAME=thedevconf

# Build image:
# docker build --no-cache --progress=plain -f $IMAGE_NAME/Containerfile -t $IMAGE_NAME:$(cat version.x.txt).$(cat version.y.txt) . 
# podman build --no-cache --progress=plain -f $IMAGE_NAME/Containerfile -t $IMAGE_NAME:$(cat version.x.txt).$(cat version.y.txt) . 

# Log in to ECR:
# AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
# AWS_REGION=$(aws configure get region)
# aws ecr get-login-password --region $AWS_REGION | docker login --user_name AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

# Tag and push to ECR:
# docker tag $IMAGE_NAME:$(cat version.x.txt).$(cat version.y.txt) $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$(cat version.x.txt).$(cat version.y.txt)
# docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME:$(cat version.x.txt).$(cat version.y.txt)  

# Tag and push to docker hub:
# docker tag $IMAGE_NAME:$(cat version.x.txt).$(cat version.y.txt) $REGISTRY_USER_NAME/$IMAGE_NAME:$(cat version.x.txt).$(cat version.y.txt)
# docker push docker.io/$REGISTRY_USER_NAME/$IMAGE_NAME:$(cat version.x.txt).$(cat version.y.txt)

ARG UBI="public.ecr.aws/amazoncorretto/amazoncorretto:25-jdk"
FROM ${UBI}

# Root level
USER root

# Single-shot DNF layer
RUN dnf update -y && \
    dnf install -y "which" "make" "maven" && \
    dnf clean all 


## Create User
ARG USER_NAME="code"
ENV USER_NAME="${USER_NAME}"
ARG USER_HOME="/home/${USER_NAME}"
ENV USER_HOME="${USER_HOME}"
ARG USER_UID="1001"
RUN echo "$USER_NAME:x:$USER_UID:$USER_UID:$USER_NAME User:/home/$USER_NAME:/bin/sh" >> /etc/passwd && \
    echo "$USER_NAME:x:$USER_UID:" >> /etc/group && \
    mkdir -p $USER_HOME && \
    chown -R "$USER_UID:$USER_UID" "$USER_HOME"



# User level
USER $USER_NAME

RUN bash -c "\
    echo Initializing UBI user_home[${USER_HOME}] && \
    mkdir -p $USER_HOME/.local/bin && \
    ln -s $USER_HOME/jre/bin/java $USER_HOME/.local/bin/java"

# Jlink minimal JRE
ARG JAVA_MODULES="\
java.base,\
java.compiler,\
java.desktop,\
java.logging,\
java.management,\
java.naming,\
java.net.http,\
java.rmi,\
java.security.jgss,\
java.security.sasl,\
java.sql,\
java.transaction.xa,\
java.xml,\
jdk.compiler,\
jdk.crypto.ec,\
jdk.unsupported"

RUN bash -c "jlink \
    --add-modules "$JAVA_MODULES" \
    --compress=zip-2 \
    --no-header-files \
    --no-man-pages \
    --output $USER_HOME/jre"

ENV JAVA_HOME=$USER_HOME/jre

# Debugging helpers
# RUN which java && java -version
# RUN which node && node -v

# Copy source code
WORKDIR "/home/$USER_NAME/src"
COPY --chown=$USER_NAME  . .

RUN mvn -f fg-api verify

 # Run build
RUN bash -c "echo user_home=${USER_HOME}; rm -rf \"$USER_HOME/src/*\""
